export const SERVICE_CATEGORIES = [
  "Medical Clinic & Urgent Care",
  "Dental Services",
  "Mental Health Counseling",
  "Home Healthcare",
  "Telemedicine Services",
  "Physical Therapy & Rehabilitation",
  "Medical Laboratory & Diagnostics",
  "Medical Billing & Coding",
  "Gym / Fitness Center",
  "Personal Training",
  "Yoga / Pilates Studio",
  "Nutritionist / Dietitian Services",
  "Massage Therapy Clinic",
  "Wellness Spa",
  "Meditation & Mindfulness Training",
  "Health Coaching",
  "Holistic Therapy Services",
  "Hair Salon / Barber Shop",
  "Nail Salon",
  "Makeup Artist Services",
  "Personal Stylist / Image Consultant",
  "Skincare & Esthetician Services",
  "Tattoo & Piercing Studio",
  "Plumbing Services",
  "Electrical Services",
  "HVAC Services",
  "Roofing Services",
  "Painting Services",
  "Flooring Installation",
  "Handyman Services",
  "Appliance Repair",
  "Home Remodeling & Renovation",
  "Locksmith Services",
  "Residential Cleaning",
  "Commercial Cleaning",
  "Landscaping & Lawn Care",
  "Pest Control Services",
  "Pool Maintenance",
  "Junk Removal",
  "Pressure Washing",
  "Carpet & Upholstery Cleaning",
  "Window Cleaning",
  "Real Estate Agency",
  "Property Management",
  "Real Estate Appraisal",
  "Home Inspection",
  "Interior Design",
  "Home Staging",
  "Architectural Design",
  "Tutoring Services",
  "Test Prep Coaching",
  "Language Instruction",
  "Online Course Provider",
  "Corporate Training Services",
  "Driving School",
  "Vocational & Trade Training",
  "Music or Art Lessons",
  "Educational Consulting",
  "Career Coaching",
  "Management Consulting",
  "HR & Recruitment Services",
  "IT Support & Consulting",
  "Legal Services",
  "Accounting & Bookkeeping",
  "Financial Advisory & Planning",
  "Insurance Brokerage",
  "Virtual Assistant Services",
  "Translation Services",
  "Graphic Design Services",
  "Web Design & Development",
  "Content Writing & Copywriting",
  "SEO & Digital Marketing",
  "Advertising Services",
  "Public Relations Services",
  "Photography & Videography",
  "Printing & Copying Services",
  "Travel Agency & Tour Planning",
  "Event Planning",
  "Catering Services",
  "Hotel & Lodging",
  "Party Equipment Rental",
  "Event Entertainment",
  "Valet Parking Services",
  "Event Staffing Services",
  "Car Rental Services",
  "Taxi & Rideshare Services",
  "Courier & Delivery Services",
  "Moving & Relocation Services",
  "Freight & Logistics",
  "Auto Repair & Maintenance",
  "Towing & Roadside Assistance",
  "Limousine & Chauffeur Services",
  "Childcare / Daycare",
  "Senior Care Services",
  "Pet Grooming",
  "Pet Sitting & House Sitting",
  "Personal Concierge & Errand Services",
  "Life Coaching",
  "Notary Public Services",
  "Private Security Services",
] as const;

export type ServiceCategory = typeof SERVICE_CATEGORIES[number];
