export const SERVICE_CATEGORIES = [
  "Accounting & Bookkeeping",
  "Advertising Services",
  "Appliance Repair",
  "Architectural Design",
  "Auto Repair & Maintenance",
  "Car Rental Services",
  "Career Coaching",
  "Carpet & Upholstery Cleaning",
  "Catering Services",
  "Childcare / Daycare",
  "Commercial Cleaning",
  "Content Writing & Copywriting",
  "Corporate Training Services",
  "Courier & Delivery Services",
  "Dental Services",
  "Driving School",
  "Educational Consulting",
  "Electrical Services",
  "Event Entertainment",
  "Event Planning",
  "Event Staffing Services",
  "Financial Advisory & Planning",
  "Flooring Installation",
  "Freight & Logistics",
  "Graphic Design Services",
  "Gym / Fitness Center",
  "Hair Salon / Barber Shop",
  "Handyman Services",
  "Health Coaching",
  "Holistic Therapy Services",
  "Home Healthcare",
  "Home Inspection",
  "Home Remodeling & Renovation",
  "Home Staging",
  "Hotel & Lodging",
  "HR & Recruitment Services",
  "HVAC Services",
  "Insurance Brokerage",
  "Interior Design",
  "IT Support & Consulting",
  "Junk Removal",
  "Landscaping & Lawn Care",
  "Language Instruction",
  "Legal Services",
  "Life Coaching",
  "Limousine & Chauffeur Services",
  "Locksmith Services",
  "Makeup Artist Services",
  "Management Consulting",
  "Massage Therapy Clinic",
  "Medical Billing & Coding",
  "Medical Clinic & Urgent Care",
  "Medical Laboratory & Diagnostics",
  "Meditation & Mindfulness Training",
  "Mental Health Counseling",
  "Moving & Relocation Services",
  "Music or Art Lessons",
  "Nail Salon",
  "Notary Public Services",
  "Nutritionist / Dietitian Services",
  "Online Course Provider",
  "Painting Services",
  "Party Equipment Rental",
  "Personal Concierge & Errand Services",
  "Personal Stylist / Image Consultant",
  "Personal Training",
  "Pest Control Services",
  "Pet Grooming",
  "Pet Sitting & House Sitting",
  "Photography & Videography",
  "Physical Therapy & Rehabilitation",
  "Plumbing Services",
  "Pool Maintenance",
  "Pressure Washing",
  "Printing & Copying Services",
  "Private Security Services",
  "Property Management",
  "Public Relations Services",
  "Real Estate Agency",
  "Real Estate Appraisal",
  "Residential Cleaning",
  "Roofing Services",
  "SEO & Digital Marketing",
  "Senior Care Services",
  "Skincare & Esthetician Services",
  "Tattoo & Piercing Studio",
  "Taxi & Rideshare Services",
  "Telemedicine Services",
  "Test Prep Coaching",
  "Towing & Roadside Assistance",
  "Translation Services",
  "Travel Agency & Tour Planning",
  "Tutoring Services",
  "Valet Parking Services",
  "Virtual Assistant Services",
  "Vocational & Trade Training",
  "Web Design & Development",
  "Wellness Spa",
  "Window Cleaning",
  "Yoga / Pilates Studio",
] as const;

export type ServiceCategory = typeof SERVICE_CATEGORIES[number];
